syntax on
syntax enable

set ts=2
set sw=2
set expandtab
set guifont=Monaco:h12
set nu

set laststatus=2

set ic
set smartcase
" Generic settings
set history=1000
set undolevels=1000

" No backups nor swapfiles
set nobackup
set noswapfile

" Map leader key
let mapleader = ","

noremap <leader>o <Esc>:CtrlP<CR>
noremap <leader>tb <Esc>:TagbarToggle<CR>


nmap <silent> <leader>rn :set relativenumber<CR>
nmap <silent> <leader>an :set number<CR>


" Past and keep
vnoremap <leader>p "_dP

map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_

"Edit vimrc
nmap <silent> <leader>ev :e $MYVIMRC<CR>
"Reload vimrc
nmap <silent> <leader>rv :so $MYVIMRC<CR>

"Nerdtree
nmap <silent> <leader>n :NERDTreeToggle<CR>
nmap <silent> <leader>bm :NERDTreeMirror<CR>

"CommandT
nmap <silent> <leader>f :CommandT <CR>

"Fugitive git bindings
nmap <silent> <leader>gs :Gstatus<CR>
nmap <silent> <leader>gc :Gcommit<CR>
nmap <silent> <leader>gd :Gdiff<CR>

"Move bw windows
nmap <silent> <leader>k :wincmd k<CR>
nmap <silent> <leader>j :wincmd j<CR>
nmap <silent> <leader>h :wincmd h<CR>
nmap <silent> <leader>l :wincmd l<CR>
noremap <silent> <C-h> :bprev<CR>
noremap <silent> <C-l> :bnext<CR>
noremap <silent> <C-c> :bd<CR>

"tslime
vmap <C-s><C-s> <Plug>SendSelectionToTmux
nmap <C-s><C-s> <Plug>NormalModeSendToTmux
nmap <C-s>r <Plug>SetTmuxVars


"align

vmap <leader>css :sort<bar>:Align :\zs<CR>
vmap <leader>rgb :s/\s\s/ /ge<bar>:s/\s/,/g<CR>


"Learn proper vim
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

"Pathogen
call pathogen#infect()
call pathogen#helptags()

"solarized
se t_Co=256
let g:solarized_termcolors=256

set background=dark
colorscheme solarized


"Set red background for text that goes beyond 80 cols
augroup vimrc_autocmds
  au!
  autocmd BufRead * highlight OverLength ctermbg=red ctermfg=white guibg=#592929
  autocmd BufRead * match OverLength /\%81v.*/
augroup END

"set statusline=%<%t\ [%{strlen(&fenc)?&fenc:'none'}] "file name and encoding
"set statusline+=%m      "modified flag
"
"set statusline+=%{SyntasticStatuslineFlag()}

autocmd FileType ruby,eruby,yaml set ai sw=2 sts=2 et
au BufNewFile,BufRead *.god 	set filetype=ruby

if has("autocmd")
  filetype indent on
endif

runtime! autoload/fugitive.vim

"if exists('*fugitive#statusline')
"    set statusline+=%=\ %{fugitive#statusline()}
"    "let &statusline='%= %t %{fugitive#statusline()}'
"  endif

"airline
"let g:airline#extensions#tabline#enabled = 1


autocmd FileType cucumber compiler cucumber | setl makeprg=cucumber\ \"%:p\"
autocmd FileType ruby
      \ if expand('%') =~# '_test\.rb$' |
      \   compiler rubyunit | setl makeprg=testrb\ \"%:p\" |
      \ elseif expand('%') =~# '_spec\.rb$' |
      \   compiler rspec | setl makeprg=rspec\ \"%:p\" |
      \ else |
      \   compiler ruby | setl makeprg=ruby\ -wc\ \"%:p\" |
      \ endif
autocmd User Bundler
      \ if &makeprg !~# 'bundle' | setl makeprg^=bundle\ exec\  | endif

  " Strip trailing whitespace
function! <SID>StripTrailingWhitespaces()
  " Preparation: save last search, and cursor position.
  let _s=@/
  let l = line(".")
  let c = col(".")
  " Do the business:
  %s/\s\+$//e
  " Clean up: restore previous search history, and cursor position
  let @/=_s
call cursor(l, c)
  endfunction

autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

let g:turbux_command_rspec='rspec'


let g:airline_powerline_fonts = 1
